#!/bin/dash

if [ -d ".legit" ]
then
   if [ -s ".legit/commits/logfile" ]
   then
      if [ $# -gt 0 ]
      then
         echo "usage: legit-log"
      else
         tac ".legit/commits/logfile"
      fi
   else
      echo "legit-log: error: your repository does not have any commits yet"
   fi
else
   echo "legit-log: error: no .legit directory containing legit repository exists"
fi
