#!/bin/dash

if [ $# -eq 0 ]
then
   if [ -d ".legit" ]
   then
      echo "legit-init: error: .legit already exists"
   else
      mkdir ".legit"
      mkdir ".legit/index"
      mkdir ".legit/commits"
      touch ".legit/commits/logfile"
      mkdir ".legit/branches"
      echo "Initialized empty legit repository in .legit"
   fi
else
   echo "usage: legit-init"
fi
